apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot
  labels:
    app: parrot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parrot
  template:
    metadata:
      labels:
        app: parrot
    spec:
      containers:
      - name: parrot
        image: freelancer08/parrot:1
        imagePullPolicy: Always
        resources:
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: parrot
  labels:
    app: parrot
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: parrot
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: parrot
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: parrot