apiVersion: apps/v1
kind: Deployment
metadata:
  name: captainkube
  labels:
    app: captainkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captainkube
  template:
    metadata:
      labels:
        app: captainkube
    spec:
      containers:
      - name: captainkube
        image: freelancer08/captainkube:2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
